// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "tags": [
        {
            "description": "Subscription management",
            "name": "subscription"
        },
        {
            "description": "sing-box container lifecycle and config management",
            "name": "singbox"
        },
        {
            "description": "WireGuard key generation and client configuration",
            "name": "wireguard"
        },
        {
            "description": "Self-signed certificate management",
            "name": "certificate"
        },
        {
            "description": "REALITY keypair generation and TLS checks",
            "name": "reality"
        },
        {
            "description": "Node health probing and latency measurement",
            "name": "prober"
        },
        {
            "description": "Proxy speed testing",
            "name": "speedtest"
        },
        {
            "description": "WARP registration, licensing, and endpoint scanning",
            "name": "warp"
        },
        {
            "description": "System health and status endpoints",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Singbox UI API",
	Description:      "API for managing sing-box, WireGuard, subscriptions, probing, and WARP",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
