// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Returns the server health status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/prober/best": {
            "get": {
                "description": "Returns the online node with the lowest measured latency",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Get best node",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prober/nodes": {
            "put": {
                "description": "Replaces the entire set of probed nodes with the given list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Update prober nodes",
                "parameters": [
                    {
                        "description": "List of nodes",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/prober.ProberNodesRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a single new node to the prober's node list",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Add prober node",
                "parameters": [
                    {
                        "description": "Node details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/prober.ProberNodeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes all nodes from the prober's node list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Clear prober nodes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.MessageResponse"
                        }
                    }
                }
            }
        },
        "/prober/nodes/{tag}": {
            "delete": {
                "description": "Removes a single node from the prober's node list by tag",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Remove prober node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node tag",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prober/online": {
            "get": {
                "description": "Returns all nodes that are currently online",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Get online nodes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/prober/results": {
            "get": {
                "description": "Returns probe results for all registered nodes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Get all probe results",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/prober/results/{tag}": {
            "get": {
                "description": "Returns the probe result for a specific node identified by its tag",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Get probe result by tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node tag",
                        "name": "tag",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prober/save": {
            "post": {
                "description": "Saves probe results to the subscription service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Save probe results",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.MessageResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/prober/start": {
            "post": {
                "description": "Starts the periodic probing loop",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Start prober",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.MessageResponse"
                        }
                    }
                }
            }
        },
        "/prober/status": {
            "get": {
                "description": "Returns the current prober engine status including running state and probe counts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Get prober status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.ProberStatus"
                        }
                    }
                }
            }
        },
        "/prober/stop": {
            "post": {
                "description": "Stops the periodic probing loop",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Stop prober",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.MessageResponse"
                        }
                    }
                }
            }
        },
        "/prober/sync": {
            "post": {
                "description": "Imports proxy nodes from the subscription service and adds them to the prober",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "prober"
                ],
                "summary": "Sync nodes from subscription",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/prober.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/certificate": {
            "get": {
                "description": "Returns metadata about the stored TLS certificate including validity and fingerprint",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificate"
                ],
                "summary": "Get certificate info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/certificate.CertificateInfo"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Generates a self-signed TLS certificate for the given domain and validity period, saves it to the singbox directory",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificate"
                ],
                "summary": "Generate self-signed certificate",
                "parameters": [
                    {
                        "description": "Domain and validity period",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/certificate.GenerateCertRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/certificate.CertificateInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/certificate/upload": {
            "post": {
                "description": "Uploads cert.pem and key.pem files as multipart form data",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "certificate"
                ],
                "summary": "Upload certificate files",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Certificate file (cert.pem)",
                        "name": "cert",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Private key file (key.pem)",
                        "name": "key",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/certificate.CertificateInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/config": {
            "get": {
                "description": "Returns the current sing-box configuration as raw JSON",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Get sing-box config",
                "responses": {
                    "200": {
                        "description": "Raw config JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Saves the sing-box configuration from the raw request body",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Save sing-box config",
                "responses": {
                    "200": {
                        "description": "config saved",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/containers": {
            "get": {
                "description": "Returns all sing-box Docker containers across all named instances",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "List all containers",
                "responses": {
                    "200": {
                        "description": "list of containers",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/ensure-image": {
            "post": {
                "description": "Pulls the sing-box Docker image if not already present",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Ensure sing-box image",
                "responses": {
                    "200": {
                        "description": "image ready",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/instances": {
            "get": {
                "description": "Returns all named configuration instances with their status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "List named configs",
                "responses": {
                    "200": {
                        "description": "list of configs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/instances/{name}": {
            "delete": {
                "description": "Deletes a named configuration and stops its container if running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Delete named config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "config deleted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/instances/{name}/check": {
            "post": {
                "description": "Validates the JSON syntax of a named configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Check named config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/singbox.CheckConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/instances/{name}/config": {
            "get": {
                "description": "Returns a named configuration as raw JSON",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Get named config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Raw config JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Saves a named configuration, validates it, and returns the result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Save named config",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name (2-10 chars, start with letter)",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/singbox.CheckConfigResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/instances/{name}/logs": {
            "get": {
                "description": "Returns the logs for a named sing-box container instance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Get named container logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "logs for container",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/instances/{name}/run": {
            "post": {
                "description": "Starts a named sing-box container instance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Run named container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/singbox.NamedInstanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/instances/{name}/status": {
            "get": {
                "description": "Returns the running status and container ID of a named instance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Get named container status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/singbox.NamedInstanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/instances/{name}/stop": {
            "post": {
                "description": "Stops a named sing-box container instance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Stop named container",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Config name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/singbox.NamedInstanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/logs": {
            "get": {
                "description": "Returns the logs from the sing-box Docker container",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Get sing-box logs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/singbox.LogResponse"
                        }
                    }
                }
            }
        },
        "/singbox/reality/check-tls": {
            "post": {
                "description": "Checks if a remote server supports TLS 1.3 (required for Reality disguise domain)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reality"
                ],
                "summary": "Check TLS 1.3 support",
                "parameters": [
                    {
                        "description": "Server domain and port",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/certificate.CheckTLS13Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/certificate.CheckTLS13Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/reality/keypair": {
            "post": {
                "description": "Generates a random x25519 key pair for use with Reality TLS",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reality"
                ],
                "summary": "Generate Reality key pair",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/certificate.RealityKeypairResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/reality/public-key": {
            "post": {
                "description": "Derives the public key from a base64-encoded x25519 private key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reality"
                ],
                "summary": "Derive Reality public key",
                "parameters": [
                    {
                        "description": "Private key",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/certificate.DerivePublicKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/certificate.RealityKeypairResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/run": {
            "post": {
                "description": "Starts the sing-box Docker container with the current configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Run sing-box",
                "responses": {
                    "200": {
                        "description": "container started",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/status": {
            "get": {
                "description": "Returns whether the sing-box container is currently running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Check sing-box status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/singbox.StatusResponse"
                        }
                    }
                }
            }
        },
        "/singbox/stop": {
            "post": {
                "description": "Stops the running sing-box Docker container",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Stop sing-box",
                "responses": {
                    "200": {
                        "description": "container stopped",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/singbox/version": {
            "get": {
                "description": "Returns the version of the installed sing-box Docker image",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "singbox"
                ],
                "summary": "Get sing-box version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/singbox.VersionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/speedtest/start": {
            "post": {
                "description": "Starts a speed test for all loaded proxy nodes",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "speedtest"
                ],
                "summary": "Start speed test",
                "responses": {
                    "200": {
                        "description": "speed test started",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/speedtest/status": {
            "get": {
                "description": "Returns the current speed test state including progress and results",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "speedtest"
                ],
                "summary": "Get speed test status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/speedtest.SpeedTestState"
                        }
                    }
                }
            }
        },
        "/speedtest/stop": {
            "post": {
                "description": "Stops the currently running speed test if one is in progress",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "speedtest"
                ],
                "summary": "Stop speed test",
                "responses": {
                    "200": {
                        "description": "stop requested",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/subscription": {
            "get": {
                "description": "Returns all subscriptions with total node counts",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Get all subscriptions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new subscription by URL and parses its proxy nodes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Add a new subscription",
                "parameters": [
                    {
                        "description": "Subscription details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subscription.AddSubscriptionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/nodes": {
            "get": {
                "description": "Returns all proxy nodes across all subscriptions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Get all proxy nodes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/refresh-all": {
            "post": {
                "description": "Re-fetches and parses all subscriptions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Refresh all subscriptions",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/user-agents": {
            "get": {
                "description": "Returns available user-agent presets for subscription fetching",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Get user agent presets",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/subscription/{id}": {
            "delete": {
                "description": "Removes a subscription by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Delete a subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/{id}/refresh": {
            "post": {
                "description": "Re-fetches and parses a subscription by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Refresh a single subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/subscription/{id}/settings": {
            "patch": {
                "description": "Updates auto-update and interval settings for a subscription",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Update subscription settings",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Settings",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subscription.UpdateSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/warp/account": {
            "get": {
                "description": "Returns the stored WARP device account info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warp"
                ],
                "summary": "Get WARP account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/warp.WarpRecord"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes the stored WARP device account",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warp"
                ],
                "summary": "Delete WARP account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/warp/license": {
            "post": {
                "description": "Binds a WARP+ license key to the registered device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warp"
                ],
                "summary": "Bind WARP+ license",
                "parameters": [
                    {
                        "description": "License key",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/warp.LicenseBindRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/warp.WarpRecord"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/warp/register": {
            "post": {
                "description": "Registers a new WARP device with Cloudflare",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warp"
                ],
                "summary": "Register WARP device",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/warp.WarpRegisterResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/warp/scan": {
            "post": {
                "description": "Scans for available WARP endpoints with best latency",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "warp"
                ],
                "summary": "Scan WARP endpoints",
                "parameters": [
                    {
                        "description": "Scan configuration (uses defaults if omitted)",
                        "name": "config",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/warp.WarpScanConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/warp.WarpEndpointResult"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wireguard/client-config": {
            "get": {
                "description": "Returns the saved WireGuard client configuration as raw JSON",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Get client config",
                "responses": {
                    "200": {
                        "description": "client config JSON",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Saves raw JSON as the WireGuard client configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Save client config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wireguard.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wireguard/client-files": {
            "get": {
                "description": "Returns a list of all saved WireGuard .conf files",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "List client config files",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/wireguard.ClientConfigFile"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wireguard/keygen": {
            "post": {
                "description": "Generates or retrieves cached WireGuard key pair. Optionally associates with an IP address",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Generate WireGuard keys",
                "parameters": [
                    {
                        "description": "Optional IP address",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/wireguard.WireGuardKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wireguard.WireGuardKeyPair"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wireguard/keys-cache": {
            "get": {
                "description": "Returns all cached WireGuard key entries with their associated IPs",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Get keys cache",
                "responses": {
                    "200": {
                        "description": "keyed by IP",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wireguard/pubkey": {
            "post": {
                "description": "Derives a WireGuard public key from a base64-encoded private key",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Derive public key",
                "parameters": [
                    {
                        "description": "Private key",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wireguard.DerivePublicKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "public key",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wireguard/public-ip": {
            "get": {
                "description": "Returns the server's detected public IPv4 address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Get public IP",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wireguard.PublicIPResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wireguard/save-client-file": {
            "post": {
                "description": "Saves a .conf file content for a specific client. Accepts JSON body or multipart form",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wireguard"
                ],
                "summary": "Save client config file",
                "parameters": [
                    {
                        "description": "Client file info",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/wireguard.SaveClientFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/wireguard.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/docs.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "certificate.CertificateInfo": {
            "description": "Certificate metadata including validity period and fingerprint",
            "type": "object",
            "properties": {
                "cert_path": {
                    "type": "string",
                    "example": "/data/singbox/cert.pem"
                },
                "common_name": {
                    "type": "string",
                    "example": "example.com"
                },
                "fingerprint": {
                    "type": "string",
                    "example": "SHA256:abc123def456"
                },
                "key_path": {
                    "type": "string",
                    "example": "/data/singbox/key.pem"
                },
                "valid_from": {
                    "type": "string",
                    "example": "2026-06-01T00:00:00Z"
                },
                "valid_to": {
                    "type": "string",
                    "example": "2027-06-01T00:00:00Z"
                }
            }
        },
        "certificate.CheckTLS13Request": {
            "description": "Request to check if a server supports TLS 1.3 (required for Reality disguise domain)",
            "type": "object",
            "required": [
                "server"
            ],
            "properties": {
                "port": {
                    "type": "integer",
                    "example": 443
                },
                "server": {
                    "type": "string",
                    "example": "example.com"
                }
            }
        },
        "certificate.CheckTLS13Response": {
            "description": "Result of TLS 1.3 support check",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "connection failed"
                },
                "supported": {
                    "type": "boolean",
                    "example": true
                },
                "tls_version": {
                    "type": "string",
                    "example": "TLS 1.3"
                }
            }
        },
        "certificate.DerivePublicKeyRequest": {
            "description": "Request to derive a public key from a private key",
            "type": "object",
            "required": [
                "private_key"
            ],
            "properties": {
                "private_key": {
                    "type": "string",
                    "example": "ARVXKXp6V9XmXQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQ"
                }
            }
        },
        "certificate.GenerateCertRequest": {
            "description": "Request to generate a self-signed TLS certificate",
            "type": "object",
            "required": [
                "domain",
                "valid_days"
            ],
            "properties": {
                "domain": {
                    "type": "string",
                    "example": "example.com"
                },
                "valid_days": {
                    "type": "integer",
                    "example": 365
                }
            }
        },
        "certificate.RealityKeypairResponse": {
            "description": "x25519 key pair for Reality TLS",
            "type": "object",
            "properties": {
                "private_key": {
                    "type": "string",
                    "example": "ARVXKXp6V9XmXQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQ"
                },
                "public_key": {
                    "type": "string",
                    "example": "9XmXQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQmQ"
                }
            }
        },
        "docs.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "internal server error"
                },
                "message": {
                    "type": "string",
                    "example": "detailed error description"
                }
            }
        },
        "prober.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operation completed"
                }
            }
        },
        "prober.ProberNodeRequest": {
            "type": "object",
            "required": [
                "address",
                "port",
                "protocol",
                "tag"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "protocol": {
                    "type": "string"
                },
                "tag": {
                    "type": "string"
                }
            }
        },
        "prober.ProberNodesRequest": {
            "type": "object",
            "required": [
                "nodes"
            ],
            "properties": {
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/prober.ProberNodeRequest"
                    }
                }
            }
        },
        "prober.ProberStatus": {
            "description": "Current prober engine status",
            "type": "object",
            "properties": {
                "last_probe_time": {
                    "type": "string",
                    "example": "2026-06-01T12:00:00Z"
                },
                "offline_nodes": {
                    "type": "integer",
                    "example": 3
                },
                "online_nodes": {
                    "type": "integer",
                    "example": 5
                },
                "running": {
                    "type": "boolean",
                    "example": true
                },
                "total_probes": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "singbox.CheckConfigResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "Config is valid"
                },
                "valid": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "singbox.LogResponse": {
            "type": "object",
            "properties": {
                "logs": {
                    "type": "string",
                    "example": "2026/06/01 12:00:00 starting..."
                }
            }
        },
        "singbox.NamedInstanceResponse": {
            "type": "object",
            "properties": {
                "containerId": {
                    "type": "string",
                    "example": "abc123def456"
                },
                "message": {
                    "type": "string",
                    "example": "Operation completed"
                },
                "name": {
                    "type": "string",
                    "example": "my-config"
                }
            }
        },
        "singbox.StatusResponse": {
            "type": "object",
            "properties": {
                "containerId": {
                    "type": "string",
                    "example": "abc123def456"
                },
                "running": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "singbox.VersionResponse": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "example": "1.10.0"
                }
            }
        },
        "speedtest.SpeedTestState": {
            "type": "object",
            "properties": {
                "download_speed": {
                    "type": "number",
                    "example": 15.5
                },
                "error": {
                    "type": "string",
                    "example": "timeout"
                },
                "latency_ms": {
                    "type": "integer",
                    "example": 120
                },
                "progress": {
                    "type": "integer",
                    "example": 50
                },
                "running": {
                    "type": "boolean",
                    "example": true
                },
                "status": {
                    "type": "string",
                    "example": "testing..."
                },
                "tag": {
                    "type": "string",
                    "example": "my-proxy"
                }
            }
        },
        "subscription.AddSubscriptionRequest": {
            "type": "object",
            "required": [
                "name",
                "url"
            ],
            "properties": {
                "name": {
                    "type": "string",
                    "example": "My VPN Server"
                },
                "url": {
                    "type": "string",
                    "example": "https://example.com/sub"
                },
                "user_agent": {
                    "type": "string",
                    "example": "clash-meta"
                }
            }
        },
        "subscription.UpdateSettingsRequest": {
            "type": "object",
            "properties": {
                "auto_update": {
                    "type": "boolean",
                    "example": true
                },
                "update_interval": {
                    "type": "integer",
                    "example": 12
                }
            }
        },
        "warp.LicenseBindRequest": {
            "type": "object",
            "properties": {
                "license": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                }
            }
        },
        "warp.WarpAccount": {
            "type": "object",
            "properties": {
                "account_type": {
                    "type": "string",
                    "example": "free"
                },
                "id": {
                    "type": "string",
                    "example": "abcd-1234-ef56-7890"
                },
                "license": {
                    "type": "string",
                    "example": "xxxx-xxxx-xxxx-xxxx"
                },
                "premium_data": {
                    "type": "integer",
                    "example": 0
                },
                "warp_plus": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "warp.WarpConfig": {
            "type": "object",
            "properties": {
                "client_id": {
                    "type": "string",
                    "example": "abc123"
                },
                "interface": {
                    "$ref": "#/definitions/warp.WarpInterface"
                },
                "peers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/warp.WarpPeer"
                    }
                }
            }
        },
        "warp.WarpDevice": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/warp.WarpAccount"
                },
                "config": {
                    "$ref": "#/definitions/warp.WarpConfig"
                },
                "id": {
                    "type": "string",
                    "example": "abcd-1234-ef56-7890"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "warp.WarpEndpointResult": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string",
                    "example": "162.159.192.1"
                },
                "latency_ms": {
                    "type": "integer",
                    "example": 42
                },
                "loss_pct": {
                    "type": "integer",
                    "example": 0
                },
                "port": {
                    "type": "integer",
                    "example": 2408
                },
                "reachable": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "warp.WarpInterface": {
            "type": "object",
            "properties": {
                "addresses": {
                    "$ref": "#/definitions/warp.WarpInterfaceAddr"
                }
            }
        },
        "warp.WarpInterfaceAddr": {
            "type": "object",
            "properties": {
                "v4": {
                    "type": "string",
                    "example": "172.16.0.2"
                },
                "v6": {
                    "type": "string",
                    "example": "fd01:5ca1:ab1e:0000:0000:0000:0000:0002"
                }
            }
        },
        "warp.WarpPeer": {
            "type": "object",
            "properties": {
                "endpoint": {
                    "$ref": "#/definitions/warp.WarpPeerEndpoint"
                },
                "public_key": {
                    "type": "string",
                    "example": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0cVo9NFiY5pA0Is="
                }
            }
        },
        "warp.WarpPeerEndpoint": {
            "type": "object",
            "properties": {
                "host": {
                    "type": "string",
                    "example": "engage.cloudflareclient.com"
                },
                "v4": {
                    "type": "string",
                    "example": "162.159.192.1"
                },
                "v6": {
                    "type": "string",
                    "example": "2606:4700:100::1"
                }
            }
        },
        "warp.WarpRecord": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2026-06-01T00:00:00Z"
                },
                "device": {
                    "$ref": "#/definitions/warp.WarpDevice"
                },
                "private_key": {
                    "type": "string",
                    "example": "gL7fV/1GkH+3..."
                },
                "public_key": {
                    "type": "string",
                    "example": "xTIBdMd5Fq+3..."
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-06-01T00:00:00Z"
                }
            }
        },
        "warp.WarpRegisterResponse": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/warp.WarpAccount"
                },
                "config": {
                    "$ref": "#/definitions/warp.WarpConfig"
                },
                "id": {
                    "type": "string",
                    "example": "abcd-1234-ef56-7890"
                },
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "warp.WarpScanConfig": {
            "type": "object",
            "properties": {
                "concurrency": {
                    "type": "integer",
                    "example": 10
                },
                "max_candidates": {
                    "type": "integer",
                    "example": 10
                },
                "ping_times": {
                    "type": "integer",
                    "example": 3
                },
                "sample_per_range": {
                    "type": "integer",
                    "example": 3
                },
                "timeout_ms": {
                    "type": "integer",
                    "example": 5000
                },
                "top_n": {
                    "type": "integer",
                    "example": 5
                }
            }
        },
        "wireguard.ClientConfigFile": {
            "description": "Saved WireGuard client config file",
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "[Interface]\nPrivateKey = ..."
                },
                "name": {
                    "type": "string",
                    "example": "client-0.conf"
                }
            }
        },
        "wireguard.DerivePublicKeyRequest": {
            "description": "Request to derive a WireGuard public key from a private key",
            "type": "object",
            "required": [
                "private_key"
            ],
            "properties": {
                "private_key": {
                    "type": "string",
                    "example": "gL7fV/1GkH+3..."
                }
            }
        },
        "wireguard.MessageResponse": {
            "description": "Generic message response",
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operation completed"
                }
            }
        },
        "wireguard.PublicIPResponse": {
            "description": "Response containing the server's public IP address",
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "203.0.113.1"
                }
            }
        },
        "wireguard.SaveClientFileRequest": {
            "description": "Request to save a WireGuard client .conf file",
            "type": "object",
            "properties": {
                "client_index": {
                    "type": "integer",
                    "example": 0
                },
                "content": {
                    "type": "string",
                    "example": "[Interface]\nPrivateKey = ..."
                }
            }
        },
        "wireguard.WireGuardKeyPair": {
            "description": "WireGuard key pair with private and public keys",
            "type": "object",
            "properties": {
                "privateKey": {
                    "type": "string",
                    "example": "gL7fV/1GkH+3..."
                },
                "publicKey": {
                    "type": "string",
                    "example": "xTIBdMd5Fq+3..."
                }
            }
        },
        "wireguard.WireGuardKeyRequest": {
            "description": "Request to generate or retrieve cached WireGuard keys",
            "type": "object",
            "properties": {
                "ip": {
                    "type": "string",
                    "example": "10.0.0.1"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Subscription management",
            "name": "subscription"
        },
        {
            "description": "sing-box container lifecycle and config management",
            "name": "singbox"
        },
        {
            "description": "WireGuard key generation and client configuration",
            "name": "wireguard"
        },
        {
            "description": "Self-signed certificate management",
            "name": "certificate"
        },
        {
            "description": "REALITY keypair generation and TLS checks",
            "name": "reality"
        },
        {
            "description": "Node health probing and latency measurement",
            "name": "prober"
        },
        {
            "description": "Proxy speed testing",
            "name": "speedtest"
        },
        {
            "description": "WARP registration, licensing, and endpoint scanning",
            "name": "warp"
        },
        {
            "description": "System health and status endpoints",
            "name": "system"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Singbox UI API",
	Description:      "API for managing sing-box, WireGuard, subscriptions, probing, and WARP",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
